version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    
    redis:
        image: 'redis'
    
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db
            - mongo-config:/data/configdb
    
    api-server:
        build: ./web
        ports:
            - "5000:5000"
        volumes:
            - ./web:/code
        depends_on:
            - mongo
            - redis

    webserver:
        image: puckel/docker-airflow:1.10.2
        restart: always
        depends_on:
            - postgres
            - redis
            - mongo
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
volumes:
    db-data:
    mongo-config:
