version: '2.1'
services:
    redis:
        image: 'redis'
    
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db
            - mongo-config:/data/configdb
    
    api-server:
        build: ./web
        ports:
            - "5000:5000"
        environment:
            - FLASK_DEBUG=1
        volumes:
            - ./web:/code
        depends_on:
            - mongo
            - redis

volumes:
    db-data:
    mongo-config:
